name: aero
channels:
  - conda-forge
dependencies:
  - python=3.11
  - esmf
  - esmpy
  - xarray
  - dask
  - netcdf4
  - pandas
  - pyproj
  - requests
  - scipy
  - cartopy
  - hvplot
  - geoviews
  - pytest
  - ruff
  - pip
  - pip:
    - cmaqsatproc
    - git+https://github.com/bbakernoaa/xregrid.git
